---
apiVersion: jmeter.jmeter.io/v1
kind: TestRun
metadata:
  name: example-testrun2
  namespace: default
spec:
  slave:
    image: nginx:latest
  runGroups:
    group-a:
      thread: 120         # ceil(120/50) = 3 pods; pod-0 50t, pod-1 50t, pod-2 20t
      base: 50
      nodeSelector:
        kubernetes.io/os: linux
    group-b:
      thread: 80          # ceil(80/50) = 2 pods; pod-0 50t, pod-1 30t
      # base defaults to 50
