name: Jmeter Image Build and Push
on:
  push:
    branches: [ build-image ]
    tags: [ 'v*' ]
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: images/jmeter
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-jmeter:latest
            ghcr.io/${{ github.repository }}-jmeter:${{ github.sha }}